import { FolderPlus, X } from 'lucide-react'
import { useState } from 'react'
import { createPortal } from 'react-dom'
import { Button } from '../ui/Button'

export function CreateFolderModal({ onClose, onCreate, busy, error }: { onClose: () => void; onCreate: (name: string) => void; busy: boolean; error: string }) {
  const [name, setName] = useState('')
  return createPortal(<div className="posts-modal-backdrop fixed inset-0 z-[90] grid place-items-center bg-black/75 p-4 backdrop-blur-md" onMouseDown={event => { if (event.currentTarget === event.target) onClose() }}><form className="posts-modal-panel w-full max-w-md rounded-panel border border-brand-cyan/30 bg-panel p-5 shadow-panel" onSubmit={event => { event.preventDefault(); onCreate(name) }}><header className="flex items-start justify-between"><div><span className="grid size-10 place-items-center rounded-xl bg-brand-cyan/10 text-brand-cyan"><FolderPlus className="size-5" /></span><h2 className="mt-3 text-lg font-semibold">Create media folder</h2><p className="mt-1 text-xs text-text-muted">Keep campaign and brand assets organised.</p></div><button aria-label="Close" className="rounded-lg p-2 text-text-muted hover:bg-white/5" onClick={onClose} type="button"><X className="size-4" /></button></header><label className="mt-5 block text-xs text-text-muted">Folder name<input autoFocus className="mt-2 min-h-11 w-full rounded-xl border border-border-soft bg-bg/40 px-3 text-sm outline-none focus:border-brand-cyan" maxLength={60} onChange={event => setName(event.target.value)} placeholder="e.g. Summer campaign" value={name} /></label>{error && <p className="mt-3 rounded-lg border border-brand-red/20 bg-brand-red/8 p-2 text-[10px] text-brand-red">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button onClick={onClose} type="button" variant="ghost">Cancel</Button><Button disabled={busy || name.trim().length < 2} type="submit" variant="primary">Create Folder</Button></div></form></div>, document.body)
}
