import { useMemo, useState } from 'react'
import { formatAnalyticsValue } from '../../data/analyticsData'
import type { PerformancePoint } from '../../types/analytics'
import type { AudienceDemographics } from '../../types/dashboard'
import { AnalyticsCard, AnalyticsCardHeader, UnavailableState } from './AnalyticsPrimitives'

export function AudienceGrowthCard({ points, total }: { points: PerformancePoint[]; total: number | null }) {
  const maximum = Math.max(1, ...points.map((point) => point.followers))
  return <AnalyticsCard><AnalyticsCardHeader description="Follower change calculated from the daily Page follower totals returned by Meta." title="Audience Growth" />{total === null ? <UnavailableState detail="Reconnect the Page after read_insights is approved, or wait until Meta returns Page follow data." title="Audience growth unavailable" /> : <div className="px-5 pb-5"><strong className="text-2xl">{formatAnalyticsValue(total, 'compact')}</strong><p className="mt-1 text-[10px] text-text-muted">Net follower change in this period</p><div className="mt-5 flex h-40 items-end gap-1 border-b border-border-soft">{points.map((point) => <span className="group relative min-w-0 flex-1 rounded-t bg-gradient-to-t from-brand-teal/55 to-brand-cyan transition hover:brightness-125" key={point.date} style={{ height: `${Math.max(2, point.followers / maximum * 100)}%` }}><span className="pointer-events-none absolute bottom-full left-1/2 z-10 mb-1 hidden -translate-x-1/2 whitespace-nowrap rounded bg-bg px-2 py-1 text-[9px] shadow-panel group-hover:block">{point.label}: {point.followers}</span></span>)}</div><div className="mt-2 flex justify-between text-[9px] text-text-soft"><span>{points[0]?.label}</span><span>{points.at(-1)?.label}</span></div></div>}</AnalyticsCard>
}

export function AudienceDemographicsCard({ demographics, onEditSnapshot }: { demographics?: { instagram: AudienceDemographics | null; facebookSnapshot: AudienceDemographics | null }; onEditSnapshot: () => void }) {
  const available = useMemo(() => [demographics?.instagram, demographics?.facebookSnapshot].filter(Boolean) as AudienceDemographics[], [demographics])
  const [source, setSource] = useState<'instagram_api' | 'facebook_snapshot'>(available[0]?.source || 'facebook_snapshot')
  const selected = available.find(item => item.source === source) || available[0] || null
  const rows = useMemo(() => {
    if (!selected) return []
    return [...new Set(selected.ageGender.map(row => row.age))].map(age => ({
      age,
      women: selected.ageGender.find(row => row.age === age && row.gender === 'women')?.percentage || 0,
      men: selected.ageGender.find(row => row.age === age && row.gender === 'men')?.percentage || 0,
      unknown: selected.ageGender.find(row => row.age === age && row.gender === 'unknown')?.percentage || 0,
    }))
  }, [selected])
  const sourceButtons = <div className="flex flex-wrap gap-1.5">{demographics?.instagram && <button className={`rounded-lg border px-2 py-1 text-[9px] ${selected?.source === 'instagram_api' ? 'border-[#e1306c]/55 bg-[#e1306c]/10 text-[#f472b6]' : 'border-border-soft text-text-muted'}`} onClick={() => setSource('instagram_api')} type="button">Instagram live</button>}{demographics?.facebookSnapshot && <button className={`rounded-lg border px-2 py-1 text-[9px] ${selected?.source === 'facebook_snapshot' ? 'border-[#1877f2]/55 bg-[#1877f2]/10 text-[#60a5fa]' : 'border-border-soft text-text-muted'}`} onClick={() => setSource('facebook_snapshot')} type="button">Facebook snapshot</button>}<button className="rounded-lg border border-border-soft px-2 py-1 text-[9px] text-text-muted hover:border-brand-cyan/40 hover:text-brand-cyan" onClick={onEditSnapshot} type="button">{demographics?.facebookSnapshot ? 'Update snapshot' : 'Add snapshot'}</button></div>
  return <AnalyticsCard><AnalyticsCardHeader action={sourceButtons} description="Live Instagram professional-account demographics and dated Facebook Business Suite snapshots. Sources are always labelled." title="Audience Demographics" />{selected ? <div className="px-5 pb-5"><div className="mb-4 flex flex-wrap items-end justify-between gap-2"><div><strong className="text-lg">{selected.source === 'instagram_api' ? `@${selected.account.username || selected.account.name || 'Instagram'}` : selected.account.name || 'Facebook Page'}</strong><p className="mt-1 text-[10px] text-text-muted">{selected.source === 'instagram_api' ? 'Live Instagram follower data' : 'Facebook Business Suite snapshot'} · {new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(selected.capturedAt))}</p></div>{selected.audienceSize ? <span className="text-right"><b className="block text-sm">{formatAnalyticsValue(selected.audienceSize, 'compact')}</b><small className="text-[9px] text-text-soft">audience</small></span> : null}</div><div className="grid gap-2">{rows.map(row => <div className="grid grid-cols-[42px_1fr_76px] items-center gap-2" key={row.age}><span className="text-[10px] font-semibold text-text-muted">{row.age}</span><div className="flex h-2.5 overflow-hidden rounded-full bg-bg/55"><i className="bg-[#ec4899]" style={{ width: `${row.women}%` }} /><i className="bg-[#3b82f6]" style={{ width: `${row.men}%` }} /><i className="bg-text-soft" style={{ width: `${row.unknown}%` }} /></div><span className="text-right text-[9px] text-text-soft"><b className="text-[#f472b6]">{row.women.toFixed(1)}</b> / <b className="text-[#60a5fa]">{row.men.toFixed(1)}</b>%</span></div>)}</div><div className="mt-4 flex flex-wrap gap-4 text-[9px] text-text-soft"><span><i className="mr-1.5 inline-block size-2 rounded-full bg-[#ec4899]" />Women</span><span><i className="mr-1.5 inline-block size-2 rounded-full bg-[#3b82f6]" />Men</span>{selected.ageGender.some(row => row.gender === 'unknown') && <span><i className="mr-1.5 inline-block size-2 rounded-full bg-text-soft" />Unspecified</span>}</div></div> : <UnavailableState detail="Connect a professional Instagram account for automatic data, or add the age and gender percentages shown in Facebook Business Suite as a dated snapshot." title="Add a verified demographic source" />}</AnalyticsCard>
}
