import type { HeatmapCell } from '../../types/analytics'
import { AnalyticsCard, AnalyticsCardHeader, UnavailableState } from './AnalyticsPrimitives'

const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const hours = [0, 3, 6, 9, 12, 15, 18, 21]
function hourLabel(hour: number) { return hour === 0 ? '12 AM' : hour < 12 ? `${hour} AM` : hour === 12 ? '12 PM' : `${hour - 12} PM` }

export function BestTimeToPostCard({ cells }: { cells: HeatmapCell[] }) {
  const maximum = Math.max(0, ...cells.map((cell) => cell.value))
  const values = new Map(cells.map((cell) => [`${cell.day}-${cell.hour}`, cell.value]))
  return <AnalyticsCard className="xl:col-span-2"><AnalyticsCardHeader action={<select aria-label="Best time metric" className="min-h-9 rounded-xl border border-border-soft bg-bg/45 px-3 text-[10px] outline-none focus:border-brand-cyan" defaultValue="engagement"><option value="engagement">Engagement</option><option disabled value="views">Views · unavailable by hour</option><option disabled value="clicks">Clicks · unavailable by hour</option></select>} description="Calculated from the publishing time and interaction count of content returned in this period." title="Best Time to Post" />{maximum ? <div className="scrollbar-thin overflow-x-auto px-4 pb-5 sm:px-5"><div className="min-w-[620px]"><div className="grid grid-cols-[46px_repeat(8,minmax(45px,1fr))] gap-1.5">{days.map((day) => <div className="contents" key={day}><span className="self-center text-[10px] text-text-muted">{day}</span>{hours.map((hour) => { const value = values.get(`${day}-${hour}`) || 0; const intensity = maximum ? value / maximum : 0; return <span aria-label={`${day} ${hourLabel(hour)}: ${value} interactions`} className="group relative h-8 rounded-md border border-brand-cyan/8 transition hover:border-brand-cyan/45 hover:brightness-125" key={hour} style={{ backgroundColor: `rgba(20,184,166,${0.04 + intensity * 0.82})` }} title={`${value} interactions`} /> })}</div>)}<span />{hours.map((hour) => <span className="text-center text-[9px] text-text-soft" key={hour}>{hourLabel(hour)}</span>)}</div><div className="mt-4 flex items-center justify-center gap-2 text-[9px] text-text-soft"><span>Lower engagement</span>{[.08, .18, .32, .48, .65, .85].map((opacity) => <i className="size-4 rounded" key={opacity} style={{ backgroundColor: `rgba(20,184,166,${opacity})` }} />)}<span>Higher engagement</span></div></div></div> : <UnavailableState detail="Publish more posts at different times to unlock a personalised engagement heatmap for this Page." title="Not enough time-based activity" />}</AnalyticsCard>
}
