import { ArrowRight, Bot, CalendarClock, Check, CircleDollarSign, Coins, Crown, Download, FileText, Gauge, Infinity as InfinityIcon, LockKeyhole, ReceiptText, ShieldCheck, Sparkles, Trash2, UsersRound } from 'lucide-react'
import { comparisonRows, getPlan, plans } from '../../data/billingData'
import type { BillingCycle, BillingOverview, Invoice, Plan, PlanId } from '../../types/billing'
import { Availability, Button, Card, FeatureAvailabilityRow, ProgressBar, StatusBadge, Toggle } from './BillingPrimitives'

const money = (amount: number, currency = 'GBP') => new Intl.NumberFormat('en-GB', { style: 'currency', currency }).format(amount)
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)) : 'Not scheduled'

export function CurrentPlanCard({ overview, onUpgrade, onManage }: { overview: BillingOverview; onUpgrade: () => void; onManage: () => void }) {
  const plan = getPlan(overview.subscription.planId)
  const paidPrice = overview.subscription.billingCycle === 'yearly' ? plan.yearlyPrice : plan.monthlyPrice
  return <Card className="h-full overflow-hidden p-5 sm:p-6"><div className="grid h-full gap-6 lg:grid-cols-[1fr_1fr]"><div><div className="flex items-start gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl border border-brand-teal/30 bg-brand-teal/12 text-brand-cyan shadow-glow-cyan"><Crown aria-hidden="true" className="size-7" /></span><div><p className="text-xs text-text-muted">Current Plan</p><div className="mt-1 flex flex-wrap items-center gap-2"><h2 className="text-2xl font-bold">{plan.name}</h2><StatusBadge status={overview.subscription.status} /></div><p className="mt-1 text-sm text-text-muted">{plan.eyebrow}</p></div></div><div className="mt-6"><strong className="text-2xl">{plan.id === 'trial' ? '£0' : overview.subscription.legacyLifetime ? 'Legacy access' : money(paidPrice || 0)}</strong>{plan.id !== 'trial' && !overview.subscription.legacyLifetime && <span className="text-sm text-text-muted"> / {overview.subscription.billingCycle === 'yearly' ? 'year' : 'month'}</span>}<p className="mt-1 text-xs text-text-muted">{plan.id === 'trial' ? `Trial ends ${date(overview.subscription.trialEndsAt)}` : overview.subscription.legacyLifetime ? 'No renewal required' : `${overview.subscription.cancelAtPeriodEnd ? 'Ends' : 'Renews'} ${date(overview.subscription.renewalDate)}`}</p></div><div className="mt-5 grid gap-2 sm:flex">{plan.id !== 'plus' && <Button onClick={onUpgrade} tone="primary"><ArrowRight className="size-4" />Upgrade Plan</Button>}<Button disabled={!overview.subscription.canManage} onClick={onManage}>{overview.subscription.canManage ? 'Manage Subscription' : 'No paid subscription yet'}</Button></div></div><div className="grid content-center gap-3 border-t border-border-soft pt-5 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0">{plan.highlights.map((item) => <Availability available key={item}>{item}</Availability>)}{plan.id === 'trial' && <><Availability available={false}>Full Analytics</Availability><Availability available={false}>AI caption tools and AI Content Studio</Availability></>}</div></div></Card>
}

export function UsageCard({ overview, onView }: { overview: BillingOverview; onView: () => void }) {
  const plan = getPlan(overview.subscription.planId)
  const trial = plan.id === 'trial'
  return <Card className="h-full p-5"><header className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">This Month’s Usage</h2><p className="mt-1 text-xs text-text-muted">{overview.usage.periodEnd ? `Current period ends ${date(overview.usage.periodEnd)}` : 'Current billing period'}</p></div><button className="text-xs font-semibold text-brand-cyan hover:underline" onClick={onView} type="button">View details</button></header><div className="mt-5 space-y-4"><div><div className="mb-2 flex items-center justify-between text-sm"><span className="flex items-center gap-2"><UsersRound className="size-4 text-brand-cyan" />Connected Pages</span><b>{trial ? `${overview.usage.connectedPages} / 2` : 'Unlimited'}</b></div>{trial && <ProgressBar label="Connected pages" max={2} value={overview.usage.connectedPages} />}</div><Metric icon={<CalendarClock className="size-4" />} label="Scheduled Content" value={String(overview.usage.scheduledContent)} /><Metric icon={<InfinityIcon className="size-4" />} label="Posts / Videos" value="Unlimited" /><Metric icon={<Gauge className="size-4" />} label="Analytics" value={trial ? 'Locked' : 'Included'} locked={trial} /><Metric icon={<Bot className="size-4" />} label="AI Caption Actions" value={trial ? 'Locked' : 'Included'} locked={trial} /><Metric icon={<Sparkles className="size-4" />} label="AI Content Studio" value={plan.id === 'plus' ? 'Included' : 'Upgrade to Plus'} locked={plan.id !== 'plus'} /></div></Card>
}

function Metric({ icon, label, value, locked = false }: { icon: React.ReactNode; label: string; value: string; locked?: boolean }) { return <div className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2 text-text-muted">{icon}{label}</span><span className={`rounded-full border px-2 py-1 text-[10px] font-bold ${locked ? 'border-white/10 bg-white/5 text-text-soft' : 'border-brand-teal/20 bg-brand-teal/8 text-brand-cyan'}`}>{value}</span></div> }

export function BillingInformationCard({ onUpdate }: { onUpdate: () => void }) { return <Card className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-brand-teal/10 text-brand-cyan"><CircleDollarSign className="size-5" /></span><div><h2 className="font-semibold">Billing Information</h2><p className="mt-1 text-sm text-text-muted">Payment details are managed securely through Stripe.</p><p className="mt-2 text-xs text-text-soft">INXSocial does not display or store your full payment information.</p></div></div><Button className="w-full sm:w-auto" onClick={onUpdate}>Update Payment Method</Button></div></Card> }

export function InvoicesCard({ invoices, onViewAll }: { invoices: Invoice[]; onViewAll: () => void }) { return <Card className="h-full overflow-hidden"><header className="flex items-center justify-between gap-3 p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-teal/10 text-brand-cyan"><ReceiptText className="size-5" /></span><div><h2 className="font-semibold">Invoices</h2><p className="text-xs text-text-muted">View and download Stripe invoices.</p></div></div><Button onClick={onViewAll} tone="ghost">View all</Button></header>{invoices.length ? <div className="border-t border-border-soft">{invoices.slice(0, 4).map((invoice) => <InvoiceRow invoice={invoice} key={invoice.id} />)}</div> : <div className="border-t border-border-soft p-6 text-center"><FileText className="mx-auto size-7 text-text-soft" /><p className="mt-2 text-sm font-semibold">No invoices yet</p><p className="mt-1 text-xs text-text-muted">Invoices will appear here after your first Stripe payment.</p></div>}</Card> }

export function InvoiceRow({ invoice }: { invoice: Invoice }) { return <div className="grid gap-2 border-b border-border-soft px-5 py-3 last:border-0 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="text-sm font-semibold">{date(invoice.date)}</p><p className="text-xs text-text-muted">{money(invoice.amount, invoice.currency)}</p></div><StatusBadge status={invoice.status} /><div className="flex gap-1">{invoice.invoiceUrl && <a aria-label="View invoice" className="rounded-lg p-2 text-text-muted hover:bg-white/5 hover:text-white" href={invoice.invoiceUrl} rel="noreferrer" target="_blank"><FileText className="size-4" /></a>}{invoice.pdfUrl && <a aria-label="Download invoice PDF" className="rounded-lg p-2 text-text-muted hover:bg-white/5 hover:text-white" href={invoice.pdfUrl}><Download className="size-4" /></a>}</div></div> }

export function BillingCycleToggle({ value, onChange, yearlyAvailable }: { value: Exclude<BillingCycle, 'trial'>; onChange: (value: Exclude<BillingCycle, 'trial'>) => void; yearlyAvailable: boolean }) { return <div className="inline-flex rounded-xl border border-border-soft bg-bg/45 p-1"><button className={`rounded-lg px-4 py-2 text-xs font-semibold ${value === 'monthly' ? 'bg-brand-teal text-[#02130f]' : 'text-text-muted'}`} onClick={() => onChange('monthly')} type="button">Monthly</button><button className={`rounded-lg px-4 py-2 text-xs font-semibold ${value === 'yearly' ? 'bg-brand-teal text-[#02130f]' : 'text-text-muted'} disabled:cursor-not-allowed disabled:opacity-40`} disabled={!yearlyAvailable} onClick={() => onChange('yearly')} title={yearlyAvailable ? 'Pay yearly' : 'Yearly billing is not configured'} type="button">Yearly · save</button></div> }

export function ChangePlanSection({ current, cycle, availability, highlight, onChoose, onCompare, onCycle }: { current: PlanId; cycle: Exclude<BillingCycle, 'trial'>; availability: BillingOverview['billing']['availability']; highlight: boolean; onChoose: (plan: PlanId) => void; onCompare: () => void; onCycle: (cycle: Exclude<BillingCycle, 'trial'>) => void }) { const yearlyAvailable = availability.pro.yearly && availability.plus.yearly; return <Card className={`p-5 transition ${highlight ? 'border-brand-cyan/70 shadow-glow-cyan' : ''}`}><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-brand-cyan">Plans</p><h2 className="mt-1 text-xl font-semibold">Change Plan</h2><p className="mt-1 text-sm text-text-muted">Choose the access level that fits your workflow.</p></div><div className="flex flex-col gap-2 sm:items-end">{yearlyAvailable ? <BillingCycleToggle onChange={onCycle} value={cycle} yearlyAvailable /> : <span className="rounded-full border border-border-soft bg-bg/45 px-3 py-1.5 text-xs font-semibold text-text-muted">Monthly billing</span>}<button className="text-xs font-semibold text-brand-cyan hover:underline" onClick={onCompare} type="button">Compare plans</button></div></header><div className="mt-5 grid gap-4 lg:grid-cols-3">{plans.map((plan) => <PlanCard availability={availability} cycle={cycle} current={current} key={plan.id} onChoose={onChoose} plan={plan} />)}</div></Card> }

function PlusCreditPanel() {
  return <div className="mb-4 overflow-hidden rounded-2xl border border-brand-amber/30 bg-[radial-gradient(circle_at_100%_0%,rgba(245,158,11,.15),transparent_9rem),linear-gradient(145deg,rgba(20,49,52,.78),rgba(12,27,41,.92))] p-3.5 shadow-[0_14px_34px_rgba(0,0,0,.14)]">
    <div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl border border-brand-amber/25 bg-brand-amber/10 text-brand-amber"><Coins className="size-4" /></span><div><span className="text-[9px] font-bold uppercase tracking-[.15em] text-brand-amber">AI Content Studio allowance</span><p className="mt-1 text-sm font-bold text-white">500 AI Studio Credits included</p><p className="mt-1 text-[10px] leading-4 text-text-muted">Refreshes each billing period. Use them only for Image Posts, Carousels, Short Videos/Reels and UGC Ad generation.</p></div></div>
    <div className="mt-3 rounded-xl border border-white/8 bg-black/15 px-3 py-2 text-[10px] leading-4 text-text-muted"><strong className="text-white">Also included:</strong> 30 stock-footage video productions per billing period. These do not use the 500 AI Studio credits.</div>
  </div>
}

export function PlanCard({ plan, current, cycle, availability, onChoose }: { plan: Plan; current: PlanId; cycle: Exclude<BillingCycle, 'trial'>; availability: BillingOverview['billing']['availability']; onChoose: (plan: PlanId) => void }) {
  const isCurrent = plan.id === current
  const price = cycle === 'yearly' ? plan.yearlyPrice : plan.monthlyPrice
  const paidAvailable = plan.id === 'trial' || availability[plan.id][cycle]
  const rank = { trial: 0, pro: 1, plus: 2 }
  const label = isCurrent ? 'Current Plan' : rank[plan.id] > rank[current] ? `Upgrade to ${plan.name}` : current === 'trial' ? 'Trial access' : `Downgrade to ${plan.name}`
  const highlights = plan.id === 'plus' ? plan.highlights.filter((item) => !item.toLowerCase().includes('500 ai studio credits')) : plan.highlights
  return <article className={`relative flex min-h-full flex-col rounded-2xl border p-5 ${isCurrent ? 'border-brand-cyan/65 bg-brand-teal/8 shadow-glow-cyan' : 'border-border-soft bg-bg/35'}`}>
    {plan.id === 'plus' && <span className="absolute right-4 top-4 rounded-full bg-brand-purple/15 px-2 py-1 text-[9px] font-bold uppercase tracking-wide text-[#c4b5fd]">Full AI Studio</span>}
    <p className="text-xs text-text-muted">{plan.eyebrow}</p><h3 className="mt-1 text-xl font-bold">{plan.name}</h3><div className="mt-3"><strong className="text-2xl">{plan.id === 'trial' ? '£0' : money(price || 0)}</strong>{plan.id !== 'trial' && <span className="text-xs text-text-muted"> / {cycle === 'yearly' ? 'year' : 'month'}</span>}</div>
    <div className="my-5 flex-1">{plan.id === 'plus' && <PlusCreditPanel />}<div className="space-y-2.5">{highlights.map((item) => <Availability available key={item}>{item}</Availability>)}{plan.id === 'trial' && <Availability available={false}>Analytics and all AI tools</Availability>}{plan.id === 'pro' && <Availability available={false}>Full AI Content Studio generation</Availability>}</div></div>
    <Button disabled={isCurrent || !paidAvailable || (plan.id === 'trial' && current !== 'trial')} onClick={() => onChoose(plan.id)} tone={rank[plan.id] > rank[current] ? 'primary' : 'secondary'}>{paidAvailable ? label : `${plan.name} ${cycle} unavailable`}</Button>
  </article>
}

export function AccountPrivacyCard({ productUpdates, usageAlerts, saving, onProduct, onUsage, onDelete }: { productUpdates: boolean; usageAlerts: boolean; saving: boolean; onProduct: (next: boolean) => void; onUsage: (next: boolean) => void; onDelete: () => void }) { return <Card className="h-full overflow-hidden"><header className="p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-teal/10 text-brand-cyan"><ShieldCheck className="size-5" /></span><div><h2 className="font-semibold">Account & Privacy</h2><p className="text-xs text-text-muted">Manage account messages and data.</p></div></div></header><div className="border-t border-border-soft px-5"><Preference label="Product updates" description="Receive product and feature announcements." disabled={saving} checked={productUpdates} onChange={onProduct} /><Preference label="Usage limit alerts" description="Get important trial, page-limit and AI allowance warnings." disabled={saving} checked={usageAlerts} onChange={onUsage} /></div><div className="m-4 flex flex-col gap-3 rounded-xl border border-brand-red/30 bg-brand-red/7 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><Trash2 className="mt-0.5 size-5 text-brand-red" /><div><strong className="text-sm text-[#fda4af]">Delete account</strong><p className="mt-1 text-xs text-text-muted">Disconnect social accounts and permanently remove account data.</p></div></div><Button onClick={onDelete} tone="danger">Delete my account</Button></div></Card> }

function Preference({ label, description, checked, disabled, onChange }: { label: string; description: string; checked: boolean; disabled: boolean; onChange: (next: boolean) => void }) { return <div className="flex items-center justify-between gap-4 border-b border-border-soft py-4 last:border-0"><div><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-text-muted">{description}</p></div><Toggle checked={checked} disabled={disabled} label={label} onChange={onChange} /></div> }

export function SecureBillingFooter({ onLearn }: { onLearn: () => void }) { return <Card className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-teal/10 text-brand-cyan"><ShieldCheck className="size-5" /></span><div><h2 className="font-semibold">Secure billing powered by Stripe</h2><p className="mt-1 text-xs text-text-muted">Payments and payment-method updates happen through Stripe. INXSocial does not display or store full payment-card details.</p></div></div><Button className="w-full sm:w-auto" onClick={onLearn}>Learn more</Button></Card> }

export function ComparisonTable() { return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-border-soft text-xs text-text-muted"><th className="p-3">Feature</th>{plans.map((plan) => <th className="p-3" key={plan.id}>{plan.name}</th>)}</tr></thead><tbody>{comparisonRows.map((row) => <tr className="border-b border-border-soft last:border-0" key={row.label}><th className="p-3 font-medium">{row.label}</th>{plans.map((plan) => { const value = row.values[plan.id]; return <td className="p-3 text-text-muted" key={plan.id}>{value === true ? <Check className="size-4 text-brand-green" aria-label="Yes" /> : value === false ? <LockKeyhole className="size-4 text-text-soft" aria-label="No" /> : value}</td> })}</tr>)}</tbody></table></div> }

export function UsageDetails({ overview }: { overview: BillingOverview }) { const plan = getPlan(overview.subscription.planId); return <div><p className="text-sm text-text-muted">Current period: {date(overview.usage.periodStart)} – {date(overview.usage.periodEnd)}</p><div className="mt-5"><FeatureAvailabilityRow available detail={plan.connectedPagesLimit ? `${overview.usage.connectedPages} of ${plan.connectedPagesLimit} used` : `${overview.usage.connectedPages} connected`}>Connected pages</FeatureAvailabilityRow><FeatureAvailabilityRow available detail={`${overview.usage.scheduledContent} items created this period`}>Unlimited posts and videos</FeatureAvailabilityRow><FeatureAvailabilityRow available={plan.features.includes('analytics')}>Full Analytics</FeatureAvailabilityRow><FeatureAvailabilityRow available={plan.features.includes('ai_caption_writing')}>AI caption tools</FeatureAvailabilityRow><FeatureAvailabilityRow available={plan.features.includes('ai_content_studio')}>Full AI Content Studio</FeatureAvailabilityRow></div></div> }
