const router = require('express').Router();
const express = require('express');
const { requireAuth } = require('../middleware/authMiddleware');
const controller = require('../controllers/aiContentStudioController');
const nextController = require('../controllers/aiStudioNextController');
const ugcController = require('../controllers/ugcStudioController');

router.use(requireAuth);
router.get('/access', controller.access);
router.get('/credits/balance', controller.balance);
router.get('/credits/packs', controller.packs);
router.post('/credits/checkout', controller.createTopupCheckout);
router.post('/estimate', controller.estimate);
router.post('/references', express.raw({
  type: ['image/*', 'application/pdf', 'text/*', 'application/json', 'application/xml', 'application/rtf', 'application/octet-stream'],
  limit: '20mb'
}), controller.uploadReference);
router.post('/assistant/message', controller.assistantMessage);
router.post('/generate/conversational-image-post', controller.generateConversationalImagePost);
router.post('/generate/conversational-carousel', nextController.generateCarousel);
router.get('/video/models', nextController.videoModels);
router.post('/video/recommend', nextController.videoRecommend);
router.post('/video/estimate', nextController.videoEstimate);
router.post('/generate/video-studio', nextController.generateVideo);
router.get('/stock-video/access', nextController.stockVideoAccess);
router.post('/generate/stock-video', nextController.generateStockVideo);
router.post('/generate/image-post', controller.generateImagePost);
router.post('/generate/carousel-post', controller.generateCarouselPost);
router.post('/generate/short-video', controller.generateShortVideo);
router.post('/generate/ugc-ad', controller.generateUGCAd);
router.get('/ugc/overview', ugcController.overview);
router.post('/ugc/estimate', ugcController.estimate);
router.post('/ugc/brands/analyze', ugcController.analyzeBrand);
router.get('/ugc/campaigns', ugcController.listCampaigns);
router.post('/ugc/campaigns', ugcController.createCampaign);
router.get('/ugc/campaigns/:campaignId', ugcController.getCampaign);
router.get('/ugc/campaigns/:campaignId/engine', ugcController.getEngineProject);
router.delete('/ugc/campaigns/:campaignId', ugcController.removeCampaign);
router.get('/ugc/ads/:adId', ugcController.getAd);
router.patch('/ugc/ads/:adId', ugcController.updateAd);
router.post('/ugc/ads/:adId/reassemble', ugcController.reassembleAd);
router.post('/ugc/ads/:adId/regenerate', ugcController.regenerateAd);
router.post('/ugc/scenes/:sceneId/regenerate', ugcController.regenerateScene);
router.post('/ugc/avatars/generate', ugcController.generateAvatar);
router.post('/ugc/avatars/upload', ugcController.avatarUploadMiddleware, ugcController.uploadAvatar);
router.get('/ugc/avatars/:avatarId/references', ugcController.avatarReferences);
router.post('/ugc/avatars/:avatarId/references/upload', ugcController.avatarUploadMiddleware, ugcController.uploadAvatarReference);
router.get('/ugc/avatars/:avatarId/references/:referenceId/content', ugcController.avatarReferenceContent);
router.delete('/ugc/avatars/:avatarId/references/:referenceId', ugcController.removeAvatarReference);
router.get('/ugc/avatars/:avatarId/content', ugcController.avatarContent);
router.delete('/ugc/avatars/:avatarId', ugcController.removeAvatar);
router.post('/ugc/product-assets/upload', ugcController.productUploadMiddleware, ugcController.uploadProduct);
router.get('/ugc/product-assets/:assetId/content', ugcController.productContent);
router.get('/ugc/samples', ugcController.samples);
router.get('/ugc/samples/:sampleId/content', ugcController.sampleContent);
router.post('/ugc/samples/upload', ugcController.sampleUploadMiddleware, ugcController.uploadSample);
router.get('/ugc/music', ugcController.listMusic);
router.post('/ugc/events', ugcController.trackEvent);
router.get('/campaigns', controller.listCampaigns);
router.post('/campaigns', controller.createCampaign);
router.get('/campaigns/:campaignId', controller.getCampaign);
router.patch('/campaigns/:campaignId/posts/:postId', controller.updateCampaignPost);
router.post('/campaigns/:campaignId/posts/:postId/regenerate', controller.regenerateCampaignPost);
router.post('/campaigns/:campaignId/posts/:postId/generate-image', controller.generateCampaignPostImage);
router.delete('/campaigns/:campaignId', controller.deleteCampaign);
router.get('/generations/:id', controller.generationStatus);
router.post('/generations/:id/cancel', controller.cancelGeneration);
router.delete('/generations/:id', controller.dismissGeneration);
router.get('/drafts', controller.recentDrafts);
router.post('/drafts', controller.saveDraft);
router.delete('/drafts/:id', controller.deleteDraft);
router.post('/drafts/:id/send-to-posts', controller.sendDraftToPosts);
router.get('/history', controller.generationHistory);
router.get('/brand-kits', controller.brandKits);

module.exports = router;
