const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');

test('Analytics is a first-class responsive React workspace', () => {
  const router = read('frontend/src/router.tsx');
  const sidebar = read('frontend/src/components/layout/Sidebar.tsx');
  const page = read('frontend/src/components/analytics/AnalyticsPage.tsx');
  const selector = read('frontend/src/components/analytics/AnalyticsAccountSelector.tsx');
  const scopeNotice = read('frontend/src/components/analytics/AnalyticsScopeNotice.tsx');
  assert.match(router, /path: 'analytics'/);
  assert.match(sidebar, /label: 'Analytics'.*reactPath: '\/analytics'/);
  assert.match(page, /AnalyticsTabs/);
  assert.match(page, /AnalyticsAccountSelector/);
  assert.match(selector, /1 account at a time/);
  assert.match(selector, /Choose one connected account/);
  assert.match(selector, /role="radiogroup"/);
  assert.match(selector, /role="radio"/);
  assert.match(selector, /SocialPlatformIcon/);
  assert.match(selector, /onChange\(account\.analyticsKey\)/);
  assert.match(selector, /account\.displayName/);
  assert.doesNotMatch(selector, /MAX_ANALYTICS_SOURCES/);
  assert.doesNotMatch(selector, /platformFilter/);
  assert.doesNotMatch(selector, /All accounts/);
  assert.doesNotMatch(selector, /Selected accounts/);
  assert.doesNotMatch(selector, /analytics-source-picker-menu/);
  assert.match(page, /grid grid-cols-2 gap-2/);
  assert.match(page, /xl:grid-cols-6/);
  assert.match(page, /ExportReportButton/);
  assert.match(page, /AnalyticsScopeNotice/);
  assert.match(scopeNotice, /Current post performance/);
  assert.match(scopeNotice, />Live</);
  assert.match(scopeNotice, /Post metrics/);
  assert.match(scopeNotice, /Selected account/);
  assert.match(scopeNotice, /This account only/);
  assert.match(scopeNotice, /Last synced/);
  assert.match(scopeNotice, /Latest verified performance for published posts/);
});

test('Analytics uses live Post for Me platform data and derives transparent metrics without mock values', () => {
  const page = read('frontend/src/components/analytics/AnalyticsPage.tsx');
  const data = read('frontend/src/data/analyticsData.ts');
  const api = read('frontend/src/lib/analytics-api.ts');
  const service = read('src/services/postForMeAnalyticsService.js');
  const provider = read('src/services/postForMeService.js');
  const insights = read('frontend/src/components/analytics/ContentInsightsCards.tsx');
  const providerMetrics = read('frontend/src/components/analytics/ProviderMetricsCard.tsx');
  const schema = read('prisma/schema.prisma');
  const migration = read('prisma/migrations/20260918203000_add_persistent_analytics_source_cache/migration.sql');
  const server = read('src/server.js');
  assert.match(page, /fetchAnalyticsForSource/);
  assert.match(api, /\/api\/studio\/analytics\/source/);
  assert.match(service, /getPostForMeAnalytics/);
  assert.match(service, /social-account-feeds/);
  assert.match(service, /providerMetricSummary/);
  assert.match(service, /ANALYTICS_CACHE_TTL_MS/);
  assert.match(schema, /model AnalyticsSourceCache/);
  assert.match(schema, /@@unique\(\[userId, profileId, periodDays, cacheVariant\]\)/);
  assert.match(migration, /CREATE TABLE "AnalyticsSourceCache"/);
  assert.match(migration, /ON DELETE CASCADE/);
  assert.match(service, /prisma\.analyticsSourceCache\.findUnique/);
  assert.match(service, /prisma\.analyticsSourceCache\.upsert/);
  assert.match(service, /persistAnalyticsPayload/);
  assert.match(service, /runAnalyticsCacheRefreshSweep/);
  assert.match(service, /retryCooldownActive/);
  assert.match(service, /ANALYTICS_CACHE_RUNTIME_RETRY_AFTER_MS/);
  assert.match(service, /startAnalyticsCacheRuntime/);
  assert.match(server, /startAnalyticsCacheRuntime/);
  assert.doesNotMatch(service, /const analyticsCache = new Map/);
  assert.match(service, /feedPageSize/);
  assert.match(service, /String\(platform \|\| ''\)\.toLowerCase\(\) === 'facebook' \? 10 : 50/);
  assert.match(service, /params\.set\('expand', 'metrics'\)/);
  assert.match(service, /FEED_HISTORY_MAX_PAGES = 30/);
  assert.match(service, /FEED_HISTORY_MAX_POSTS = 3000/);
  assert.match(service, /seenCursors/);
  assert.match(service, /newest && newest < since\.getTime\(\)/);
  assert.match(service, /cacheState/);
  assert.match(service, /persistMetricSnapshots/);
  assert.match(service, /buildMeasuredSeries/);
  assert.match(service, /measured_snapshot_delta/);
  assert.match(service, /startAnalyticsSnapshotRuntime/);
  assert.match(service, /ANALYTICS_BACKGROUND_SNAPSHOT_ENABLED/);
  assert.match(service, /forceRefresh/);
  assert.match(service, /return await startAnalyticsRefresh/);
  assert.match(service, /startAnalyticsRefresh/);
  assert.match(service, /analyticsPayloadHasVerifiedMetrics/);
  assert.match(service, /syncStatus = verified \? 'READY' : 'PARTIAL'/);
  assert.match(service, /metric-empty refresh preserved last verified payload/);
  assert.match(service, /ANALYTICS_PARTIAL_RETRY_AFTER_MS = 5 \* 1000/);
  assert.match(service, /instagramNativeFallback/);
  assert.match(service, /getInstagramAnalytics/);
  assert.match(service, /repairRequired/);
  assert.match(service, /'ownership_mismatch'/);
  assert.match(service, /knownPublishedXEvidence/);
  assert.match(service, /xNativePostId/);
  assert.match(service, /result\.platformPostId/);
  assert.match(service, /matchesKnownXPublication/);
  assert.match(service, /prisma\.socialPublication\.findMany/);
  assert.match(service, /knownPublishedMatches/);
  assert.match(service, /platform_account_id/);
  assert.match(service, /providerUserId/);
  assert.match(service, /providerAccountMatches/);
  assert.match(service, /repairRequired: false/);
  assert.match(service, /retryable: !\(profile\.platform === 'x'/);
  assert.match(service, /integrityState:/);
  assert.match(service, /facebookPageFallback/);
  assert.match(service, /facebookPageUsername/);
  assert.match(service, /meta_graph_fallback/);
  assert.match(service, /persisted\?\.provider\?\.retryable === false/);
  assert.match(service, /'refreshing'/);
  assert.match(service, /'partial'/);
  assert.match(service, /background refresh delayed/);
  assert.doesNotMatch(service, /incrementSeries\(viewsSeries, date, metrics\.views\)/);
  assert.match(provider, /retry-after/);
  assert.match(provider, /status === 429/);
  assert.match(provider, /PROVIDER_GET_MAX_PER_SECOND/);
  assert.match(provider, /PROVIDER_GET_MAX_PER_MINUTE/);
  assert.match(provider, /reserveProviderReadSlot/);
  assert.match(provider, /CONNECTION_SYNC_TTL_MS/);
  assert.doesNotMatch(page, /mapWithConcurrency/);
  assert.doesNotMatch(page, /mergeAnalyticsResults/);
  assert.match(page, /fetchAnalyticsForSource\(selectedAccount, days, 'full', force\)/);
  assert.match(page, /analyticsKey === selectedKey/);
  assert.match(page, /backgroundRefreshing/);
  assert.match(page, /quietRefresh/);
  assert.match(page, /const selectedIsSyncing = !view \|\| manualRefreshing \|\| Boolean\(noVerifiedMetrics/);
  assert.match(page, /providerSourceState === 'ownership_mismatch'/);
  assert.match(page, /INXSocial blocked unrelated X feed data/);
  assert.match(page, /data\?\.results\?\.some/);
  assert.match(page, /analytics\.data\?\.results\?\.some/);
  assert.match(page, /Updating \$\{sourceName\}/);
  assert.match(page, /Last sync ·/);
  assert.match(page, /\(!view \|\| noVerifiedMetrics\) && <AnalyticsWorkspaceSkeleton/);
  assert.match(page, /refetchInterval: 5 \* 60_000/);
  assert.match(page, /states\.includes\('refreshing'\)/);
  assert.match(page, /return 2_000/);
  assert.match(page, /data\?\.analytics\?\.provider\?\.retryable === false/);
  assert.match(page, /states\.includes\('partial'\)/);
  assert.match(page, /return 5_000/);
  assert.match(page, /forcedSelections/);
  assert.match(page, /loadAnalytics\(force\)/);
  assert.doesNotMatch(page, /repairAnalyticsAccess/);
  assert.doesNotMatch(page, /connectPostForMePlatform/);
  assert.match(page, /Check X analytics again/);
  assert.match(page, /AnalyticsWorkspaceSkeleton active=\{selectedIsSyncing\}/);
  assert.match(page, /isPending=\{partialMetrics && !xIntegrityBlocked\}/);
  assert.match(page, /states\.includes\('stale'\)/);
  assert.match(page, /return 60_000/);
  assert.match(page, /refreshAnalyticsNow/);







  assert.match(page, /readSessionCache/);
  assert.match(page, /writeSessionCache/);
  assert.match(insights, /Content Efficiency/);
  assert.match(insights, /Publishing Rhythm/);
  assert.match(insights, /Avg interactions \/ post/);
  assert.match(page, /ContentEfficiencyCard/);
  assert.match(page, /PublishingRhythmCard/);
  assert.match(service, /platform === 'youtube'/);
  assert.match(service, /platform === 'pinterest'/);
  assert.match(service, /platform === 'x'/);
  assert.match(data, /Total Interactions/);
  assert.match(data, /analytics\.summary\.totalInteractions/);
  assert.match(data, /Interactions divided by content views/);
  assert.doesNotMatch(data, /128\.4K|2\.45M|89\.3K/);
  assert.match(page, /Analytics are just starting/);
  assert.match(page, /AnalyticsTabs active=\{activeTab\}/);
  assert.match(page, /selectedKey/);
  assert.match(page, /inx-social-analytics-source-v5/);
  assert.match(page, /inx-social-cache:analytics-v2/);
  assert.doesNotMatch(page, /No zero-filled analytics/);
  assert.doesNotMatch(page, /X feed contains posts from other accounts/);


  assert.doesNotMatch(page, /Post for Me/i);
  assert.doesNotMatch(data, /Post for Me/i);
  assert.doesNotMatch(api, /Post for Me/i);
  assert.doesNotMatch(service, /Post for Me/i);
  assert.doesNotMatch(providerMetrics, /Post for Me/i);
});

test('Analytics charts, tabs and report actions remain accessible and functional', () => {
  const page = read('frontend/src/components/analytics/AnalyticsPage.tsx');
  const chart = read('frontend/src/components/analytics/PerformanceOverTimeCard.tsx');
  const tabs = read('frontend/src/components/analytics/AnalyticsTabs.tsx');
  const exportButton = read('frontend/src/components/analytics/ExportReportButton.tsx');
  const motion = read('frontend/src/components/analytics/analytics-motion.css');
  assert.match(chart, /onPointerMove/);
  assert.match(chart, /Performance metric/);
  assert.match(chart, /compact\?: boolean/);
  assert.match(chart, /h-\[225px\] sm:h-\[265px\]/);
  assert.match(page, /<PerformanceOverTimeCard compact days=\{days\}/);
  assert.match(page, /<EngagementByPlatformCard breakdown=\{breakdown\} compact/);
  assert.match(page, /minmax\(280px,.62fr\)/);
  assert.match(chart, /exactDate/);
  assert.match(chart, /areaPath/);
  assert.match(chart, /Hover for exact post-date performance/);
  assert.match(chart, /hoverValue/);
  assert.match(chart, /position: Math\.round|position,/);
  assert.match(chart, /Daily publish-date points/);
  assert.match(chart, /Content Performance by Publish Date/);
  assert.doesNotMatch(chart, /Live Performance Trend/);
  assert.doesNotMatch(chart, /Content history/);
  assert.doesNotMatch(chart, /Live trend/);
  assert.match(chart, /current performance of posts published on that date/i);
  assert.match(chart, /const tension = 0\.82/);
  assert.match(chart, /Views/);
  assert.match(chart, /Interactions/);
  assert.match(chart, /Clicks/);
  assert.match(chart, /own scale/);
  assert.match(chart, /availableMetrics/);
  assert.doesNotMatch(chart, /disabled=\{item\.value <= 0\}/);
  assert.match(page, /view\?\.publishedPerformance \|\| \[\]/);
  assert.doesNotMatch(page, /aggregatePerformance|chartInterval|setInterval/);
  assert.match(tabs, /aria-current/);
  assert.doesNotMatch(page, /activeTab === 'stories'|activeTab === 'competitors'/);
  assert.doesNotMatch(read('frontend/src/data/analyticsData.ts'), /\['stories', 'Stories'\]|\['competitors', 'Competitors'\]/);
  assert.match(exportButton, /Export CSV/);
  assert.match(exportButton, /Export Excel/);
  assert.match(exportButton, /window\.print/);
  assert.match(exportButton, /mailto:/);
  assert.match(motion, /prefers-reduced-motion/);
  assert.match(motion, /analytics-chart-tooltip/);
  assert.match(motion, /cubic-bezier\(\.16,1,\.3,1\)/);
});


test('only live-data workspaces use page-level loading states', () => {
  const main = read('frontend/src/main.tsx');
  const dashboard = read('frontend/src/components/dashboard/DashboardPage.tsx');
  const calendar = read('frontend/src/components/calendar/ContentCalendarPage.tsx');
  const analytics = read('frontend/src/components/analytics/AnalyticsPrimitives.tsx');
  const posts = read('frontend/src/components/posts/PostsPage.tsx');
  const media = read('frontend/src/components/media-library/MediaLibraryPage.tsx');
  const bulk = read('frontend/src/components/bulk-scheduler/BulkSchedulerPage.tsx');
  const studio = read('frontend/src/components/ai-content-studio/AiContentStudioPage.tsx');
  const settings = read('frontend/src/components/settings/SettingsPage.tsx');
  const connections = read('frontend/src/components/connections/ConnectedAccountsPageV4.tsx');
  const billing = read('frontend/src/components/billing/BillingPlansPage.tsx');

  assert.doesNotMatch(main, /WorkspaceLoadingState|Suspense fallback/);
  assert.match(dashboard, /DashboardSkeleton/);
  assert.match(calendar, /CalendarSkeleton/);
  assert.match(analytics, /AnalyticsKpiSkeleton/);
  assert.match(analytics, /AnalyticsWorkspaceSkeleton/);
  assert.match(analytics, /active = true/);
  assert.match(analytics, /Waiting for verified account data/);
  assert.match(analytics, /Updating latest account performance/);
  assert.doesNotMatch(analytics, /Preparing your latest trend data|Bringing your analytics together/);
  assert.match(analytics, /Engagement by Platform/);

  for (const page of [posts, media, bulk, studio, settings, connections, billing]) {
    assert.doesNotMatch(page, /WorkspaceLoadingState/);
    assert.doesNotMatch(page, /if \([^\n]*(?:isLoading|isPending)[^\n]*\) return/);
  }

  assert.match(posts, /post composer remains available/i);
  assert.match(media, /Media Library interface remains available/);
  assert.match(bulk, /Bulk Scheduler interface remains available/);
  assert.match(studio, /AIStudioHeroSkeleton/);
  assert.match(settings, /Settings remain available/);
  assert.match(connections, /connection workspace remains available/);
  assert.match(billing, /BillingImmediateState/);
});

test('Dashboard uses lightweight paced analytics instead of deep feed history for every connected account', () => {
  const dashboard = read('frontend/src/components/dashboard/DashboardPage.tsx');
  const api = read('frontend/src/lib/analytics-api.ts');
  const controller = read('src/controllers/analyticsController.js');
  const service = read('src/services/postForMeAnalyticsService.js');

  assert.match(dashboard, /mapWithConcurrency\(accounts, 2/);
  assert.match(dashboard, /fetchAnalyticsForSource\(account, dashboardAnalyticsDays, 'summary'\)/);
  assert.match(api, /mode === 'summary'/);
  assert.match(controller, /feedMaxPages: 1/);
  assert.match(controller, /feedMaxPosts: 100/);
  assert.match(service, /cacheVariant/);
  assert.match(service, /feedMaxPages: 1, feedMaxPosts: 100/);
});
