const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');

test('Analytics is a first-class responsive React workspace', () => {
  const router = read('frontend/src/router.tsx');
  const sidebar = read('frontend/src/components/layout/Sidebar.tsx');
  const page = read('frontend/src/components/analytics/AnalyticsPage.tsx');
  const selector = read('frontend/src/components/analytics/AnalyticsAccountSelector.tsx');
  const scopeNotice = read('frontend/src/components/analytics/AnalyticsScopeNotice.tsx');
  assert.match(router, /path: 'analytics'/);
  assert.match(sidebar, /label: 'Analytics'.*reactPath: '\/analytics'/);
  assert.match(page, /AnalyticsTabs/);
  assert.match(page, /AnalyticsAccountSelector/);
  assert.match(selector, /Select 1–3 accounts for a clearer comparison/);
  assert.match(selector, /MAX_ANALYTICS_SOURCES = 3/);
  assert.match(selector, /platformFilter/);
  assert.match(selector, /All accounts/);
  assert.doesNotMatch(selector, /overflow-x-auto/);
  assert.match(selector, /document\.addEventListener\('pointerdown', closeOnOutside\)/);
  assert.match(selector, /setOpen\(false\)/);
  assert.match(selector, /analytics-source-picker-menu/);
  assert.match(selector, /transition-\[opacity,transform\]/);
  assert.match(page, /sm:grid-cols-2 xl:grid-cols-6/);
  assert.match(page, /ExportReportButton/);
  assert.match(page, /AnalyticsScopeNotice/);
  assert.match(scopeNotice, /Post performance analytics/);
  assert.match(scopeNotice, /Current metrics/);
  assert.match(scopeNotice, /Latest post metrics/);
  assert.match(scopeNotice, /Selected sources only/);
  assert.match(scopeNotice, /Trend tracking/);
  assert.match(scopeNotice, /complete native-platform account history/);
});

test('Analytics uses live Post for Me platform data and derives transparent metrics without mock values', () => {
  const page = read('frontend/src/components/analytics/AnalyticsPage.tsx');
  const data = read('frontend/src/data/analyticsData.ts');
  const api = read('frontend/src/lib/analytics-api.ts');
  const service = read('src/services/postForMeAnalyticsService.js');
  const provider = read('src/services/postForMeService.js');
  const insights = read('frontend/src/components/analytics/ContentInsightsCards.tsx');
  const providerMetrics = read('frontend/src/components/analytics/ProviderMetricsCard.tsx');
  assert.match(page, /fetchAnalyticsForSource/);
  assert.match(api, /\/api\/studio\/analytics\/source/);
  assert.match(service, /getPostForMeAnalytics/);
  assert.match(service, /social-account-feeds/);
  assert.match(service, /providerMetricSummary/);
  assert.match(service, /ANALYTICS_CACHE_TTL_MS/);
  assert.match(service, /limit: '100'/);
  assert.match(service, /page < 3 && rows\.length < 300/);
  assert.match(service, /cacheState/);
  assert.match(service, /persistMetricSnapshots/);
  assert.match(service, /buildMeasuredSeries/);
  assert.match(service, /measured_snapshot_delta/);
  assert.match(service, /startAnalyticsSnapshotRuntime/);
  assert.doesNotMatch(service, /incrementSeries\(viewsSeries, date, metrics\.views\)/);
  assert.match(provider, /retry-after/);
  assert.match(provider, /status === 429/);
  assert.match(page, /mapWithConcurrency\(selectedAccounts, 3/);
  assert.match(page, /refetchInterval: 5 \* 60_000/);
  assert.match(insights, /Content Efficiency/);
  assert.match(insights, /Publishing Rhythm/);
  assert.match(insights, /Avg interactions \/ post/);
  assert.match(page, /ContentEfficiencyCard/);
  assert.match(page, /PublishingRhythmCard/);
  assert.match(service, /platform === 'youtube'/);
  assert.match(service, /platform === 'pinterest'/);
  assert.match(service, /platform === 'x'/);
  assert.match(data, /Total Interactions/);
  assert.match(data, /analytics\.summary\.totalInteractions/);
  assert.match(data, /Interactions divided by content views/);
  assert.doesNotMatch(data, /128\.4K|2\.45M|89\.3K/);
  assert.match(page, /Analytics are just starting/);
  assert.match(page, /analytics are partially available/);
  assert.doesNotMatch(page, /Post for Me/i);
  assert.doesNotMatch(data, /Post for Me/i);
  assert.doesNotMatch(api, /Post for Me/i);
  assert.doesNotMatch(service, /Post for Me/i);
  assert.doesNotMatch(providerMetrics, /Post for Me/i);
});

test('Analytics charts, tabs and report actions remain accessible and functional', () => {
  const page = read('frontend/src/components/analytics/AnalyticsPage.tsx');
  const chart = read('frontend/src/components/analytics/PerformanceOverTimeCard.tsx');
  const tabs = read('frontend/src/components/analytics/AnalyticsTabs.tsx');
  const exportButton = read('frontend/src/components/analytics/ExportReportButton.tsx');
  const motion = read('frontend/src/components/analytics/analytics-motion.css');
  assert.match(chart, /onPointerMove/);
  assert.match(chart, /Performance chart interval/);
  assert.match(chart, /exactDate/);
  assert.match(chart, /areaPath/);
  assert.match(chart, /Move across the line for exact dates/);
  assert.match(chart, /Post Performance Over Time/);
  assert.match(chart, /Measured changes in the selected posts/);
  assert.match(chart, /Earlier lifetime views remain included in the KPI totals/);
  assert.match(chart, /const tension = 0\.82/);
  assert.match(page, /trackedPerformance/);
  assert.match(page, /interval === 'monthly' \? trackedPerformance/);
  assert.match(tabs, /aria-current/);
  assert.match(exportButton, /Export CSV/);
  assert.match(exportButton, /Export Excel/);
  assert.match(exportButton, /window\.print/);
  assert.match(exportButton, /mailto:/);
  assert.match(motion, /prefers-reduced-motion/);
});
